"""Render and install prompt-only Cursor adapters without owning user settings.

The managed namespace is .cursor/rules/getzilla. Rules guide an agent; they do
not register an execution harness, enforce a sandbox, or grant merge authority.
Run this module directly in an installed stack, or use getzilla_cursor.py.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import stat
import sys
import tempfile
from pathlib import Path, PurePosixPath

SOURCE = '.getzilla/cursor-rules.json'
OUTPUT = '.cursor/rules/getzilla'
MARKER = '<!-- Generated by Getzilla from .getzilla/cursor-rules.json; do not edit. -->'
MAX_SOURCE_BYTES = 65536
MAX_CORE_BYTES = 4096
MAX_RULE_BYTES = 8192
_FIELDS = {'id', 'title', 'description', 'alwaysApply', 'globs', 'references', 'instructions'}
_ID = re.compile(r'[0-9]{2}-[a-z0-9]+(?:-[a-z0-9]+)*')


class RuleError(ValueError):
    """An invalid source, unsafe target, or ownership conflict blocks the operation."""


def _root(path: Path) -> Path:
    root = Path(os.path.abspath(path))
    try:
        info = root.lstat()
    except FileNotFoundError as exc:
        raise RuleError(f'target directory does not exist: {root}') from exc
    _not_link(info, root)
    if not stat.S_ISDIR(info.st_mode):
        raise RuleError(f'not a directory: {root}')
    return root


def _not_link(info: os.stat_result, path: Path) -> None:
    reparse = getattr(info, 'st_file_attributes', 0) & getattr(stat, 'FILE_ATTRIBUTE_REPARSE_POINT', 0)
    if stat.S_ISLNK(info.st_mode) or reparse:
        raise RuleError(f'symlink or reparse point is not a managed target: {path}')


def _local(root: Path, rel: str, *, directory: bool = False) -> Path:
    """Reject detected symlinks and type collisions below the selected root."""
    path = root
    parts = PurePosixPath(rel).parts
    for index, part in enumerate(parts):
        path = path / part
        try:
            info = path.lstat()
        except FileNotFoundError:
            continue
        _not_link(info, path)
        expect_dir = index < len(parts) - 1 or directory
        if expect_dir and not stat.S_ISDIR(info.st_mode):
            raise RuleError(f'directory collision: {path}')
        if not expect_dir and not stat.S_ISREG(info.st_mode):
            raise RuleError(f'file collision: {path}')
    return path


def _read(path: Path, limit: int = MAX_SOURCE_BYTES) -> bytes:
    with path.open('rb') as stream:
        content = stream.read(limit + 1)
    if len(content) > limit:
        raise RuleError(f'file exceeds {limit}-byte budget: {path}')
    return content


def _unique_object(pairs: list[tuple[str, object]]) -> dict:
    result: dict = {}
    for key, value in pairs:
        if key in result:
            raise RuleError(f'duplicate JSON key: {key}')
        result[key] = value
    return result


def _line(value: object, name: str, limit: int = 240) -> str:
    if not isinstance(value, str) or not value.strip() or len(value) > limit:
        raise RuleError(f'invalid {name}')
    if '\n' in value or '\r' in value or '\x00' in value:
        raise RuleError(f'{name} must be one line')
    return value


def _relative(value: object, *, pattern: bool = False) -> str:
    name = _line(value, 'glob' if pattern else 'reference', 240)
    path = PurePosixPath(name)
    if (path.is_absolute() or '..' in path.parts or str(path) != name
            or any(char in name for char in ('\\', ':', ','))):
        raise RuleError(f'invalid relative path: {name}')
    if not pattern and any(char in name for char in '*?[]{}'):
        raise RuleError(f'reference must name one file: {name}')
    return name


def _specs(source: Path) -> list[dict]:
    root = _root(source)
    path = _local(root, SOURCE)
    try:
        data = json.loads(_read(path), object_pairs_hook=_unique_object)
    except (json.JSONDecodeError, UnicodeError) as exc:
        raise RuleError(f'invalid JSON in {SOURCE}: {exc}') from exc
    if not isinstance(data, dict) or set(data) != {'version', 'rules'} or type(data['version']) is not int or data['version'] != 1:
        raise RuleError('expected cursor rules version 1 and rules array')
    rules = data['rules']
    if not isinstance(rules, list) or not 1 <= len(rules) <= 32:
        raise RuleError('expected 1..32 rules')
    ids: set[str] = set()
    for rule in rules:
        if not isinstance(rule, dict) or set(rule) != _FIELDS:
            raise RuleError('invalid rule fields')
        rule_id = _line(rule['id'], 'id', 80)
        if not _ID.fullmatch(rule_id) or rule_id in ids:
            raise RuleError(f'invalid or duplicate rule id: {rule_id}')
        ids.add(rule_id)
        _line(rule['title'], 'title')
        _line(rule['description'], 'description')
        if type(rule['alwaysApply']) is not bool:
            raise RuleError(f'{rule_id}: alwaysApply must be boolean')
        for key in ('globs', 'references', 'instructions'):
            if not isinstance(rule[key], list) or len(rule[key]) > 64:
                raise RuleError(f'{rule_id}: invalid {key}')
        for glob in rule['globs']:
            _relative(glob, pattern=True)
        for ref in rule['references']:
            _relative(ref)
        if not rule['instructions'] or any(not isinstance(text, str) or not text.strip() for text in rule['instructions']):
            raise RuleError(f'{rule_id}: instructions must be nonempty strings')
        if rule['alwaysApply'] and rule['globs']:
            raise RuleError(f'{rule_id}: alwaysApply ignores globs; use a scoped rule')
    if sum(rule['alwaysApply'] for rule in rules) != 1:
        raise RuleError('exactly one bounded core rule must always apply')
    return sorted(rules, key=lambda rule: rule['id'])


def _render(rules: list[dict]) -> dict[str, bytes]:
    result: dict[str, bytes] = {}
    for rule in rules:
        lines = ['---', f'description: {json.dumps(rule["description"], ensure_ascii=False)}']
        if rule['globs']:
            lines.append(f'globs: {json.dumps(", ".join(rule["globs"]))}')
        lines += [f'alwaysApply: {str(rule["alwaysApply"]).lower()}', '---', '', MARKER, '', f'# {rule["title"]}', '']
        lines += [f'- {instruction}' for instruction in rule['instructions']]
        if rule['references']:
            lines += ['', '## Read relevant references on demand', '']
            lines += [f'- `{ref}`' for ref in rule['references']]
        content = ('\n'.join(lines) + '\n').encode('utf-8')
        budget = MAX_CORE_BYTES if rule['alwaysApply'] else MAX_RULE_BYTES
        if len(content) > budget or len(content.splitlines()) > 500:
            raise RuleError(f'{rule["id"]}: generated rule exceeds context budget')
        result[f'{OUTPUT}/{rule["id"]}.mdc'] = content
    return result


def render(source: Path) -> dict[str, bytes]:
    """Compile original rule descriptors; references stay lazy, not inlined."""
    return _render(_specs(source))


def _owned(content: bytes) -> bool:
    return MARKER.encode('utf-8') in content.splitlines()


def _plan(source: Path, target: Path | None) -> tuple[Path, dict[str, bytes], dict[str, bytes], list[str]]:
    rules = _specs(source)
    expected = _render(rules)
    root = _root(target if target is not None else source)
    for ref in sorted({ref for rule in rules for ref in rule['references']}):
        if not _local(root, ref).is_file():
            raise RuleError(f'missing reference in target: {ref}; install the Getzilla stack first')
    base = _local(root, OUTPUT, directory=True)
    existing: dict[str, bytes] = {}
    obsolete = []
    for rel in expected:
        path = _local(root, rel)
        if path.exists():
            existing[rel] = _read(path)
    if base.is_dir():
        for candidate in sorted(base.glob('*.mdc')):
            rel = candidate.relative_to(root).as_posix()
            if rel in expected:
                continue
            path = _local(root, rel)
            with path.open('rb') as stream:
                prefix = stream.read(MAX_RULE_BYTES)
            if _owned(prefix):
                obsolete.append(rel)
    return root, expected, existing, obsolete


def drift(source: Path, target: Path | None = None) -> list[str]:
    """Report missing, stale, conflicting and retired managed output; never write."""
    _, expected, existing, obsolete = _plan(source, target)
    problems = []
    for rel, content in expected.items():
        if rel not in existing:
            problems.append(f'missing {rel}')
        elif existing[rel] != content:
            status = 'stale' if _owned(existing[rel]) else 'conflict'
            problems.append(f'{status} {rel}')
    return problems + [f'obsolete {rel}' for rel in obsolete]


def _atomic_write(path: Path, content: bytes) -> None:
    fd, temporary = tempfile.mkstemp(prefix='.getzilla-', suffix='.tmp', dir=path.parent)
    try:
        with os.fdopen(fd, 'wb') as stream:
            stream.write(content)
        os.replace(temporary, path)
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)


def write(source: Path, target: Path | None = None) -> list[str]:
    """Preflight the complete plan, then replace only marked managed files.

    Writes are atomic per file, not transactional across files. Use an isolated
    workspace with one writer; this is not a hostile-concurrent-filesystem sandbox.
    """
    root, expected, existing, obsolete = _plan(source, target)
    conflicts = [rel for rel, old in existing.items() if old != expected[rel] and not _owned(old)]
    if conflicts:
        raise RuleError(f'ownership conflict; preserve or move these files explicitly: {", ".join(conflicts)}')
    changed = []
    for rel, content in expected.items():
        if existing.get(rel) == content:
            continue
        path = _local(root, rel)
        path.parent.mkdir(parents=True, exist_ok=True)
        _atomic_write(path, content)
        changed.append(f'wrote {rel}')
    for rel in obsolete:
        path = _local(root, rel)
        if not _owned(_read(path)):
            raise RuleError(f'ownership changed before retirement: {rel}')
        path.unlink()
        changed.append(f'removed {rel}')
    return changed


def main(source: Path | None = None, argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description='Check or install the prompt-only Getzilla Cursor rules.')
    parser.add_argument('--source', type=Path, default=source or Path(__file__).resolve().parents[2])
    parser.add_argument('--target', type=Path, help='Existing repository with Getzilla already installed.')
    parser.add_argument('--write', action='store_true', help='Apply managed changes; default is read-only.')
    args = parser.parse_args(argv)
    try:
        changes = write(args.source, args.target) if args.write else drift(args.source, args.target)
    except (RuleError, OSError, UnicodeError) as exc:
        print(f'cursor rules: {exc}', file=sys.stderr)
        return 2
    for change in changes:
        print(change)
    return 0 if args.write or not changes else 1


if __name__ == '__main__':
    raise SystemExit(main())
